
		// <global>
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options____global____menu
			{
				static public XVar options()
				{
					return new XVar( "welcome", new XVar( "welcomePageSkip", false,
"welcomeItems", new XVar( "logo", new XVar( "menutItem", false ),
"menu", new XVar( "menutItem", false ),
"loginform_login", new XVar( "menutItem", false ),
"username_button", new XVar( "menutItem", false ),
"welcome_item", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.Branches",
"page", "list" ),
"welcome_item1", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.OneForm_Fields",
"page", "list" ),
"welcome_item2", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.OneForm_Fields_Groups",
"page", "list" ),
"welcome_item3", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.OneForm_Values",
"page", "list" ),
"welcome_item4", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.OneForm_Value_Files",
"page", "list" ),
"welcome_item5", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.OneForm_Values_Images",
"page", "list" ) ) ),
"fields", new XVar( "gridFields", XVar.Array(),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar(  ) ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"supertop", new XVar( 0, "logo",
1, "menu",
2, "loginform_login",
3, "username_button" ),
"grid", new XVar( 0, "welcome_item",
1, "welcome_item1",
2, "welcome_item2",
3, "welcome_item3",
4, "welcome_item4",
5, "welcome_item5" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "logo", "supertop",
"menu", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"welcome_item", "grid",
"welcome_item1", "grid",
"welcome_item2", "grid",
"welcome_item3", "grid",
"welcome_item4", "grid",
"welcome_item5", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar( "menu", 3,
"username_button", 3,
"loginform_login", 3 ) ),
"itemsByType", new XVar( "logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"welcome_item", new XVar( 0, "welcome_item",
1, "welcome_item1",
2, "welcome_item2",
3, "welcome_item3",
4, "welcome_item4",
5, "welcome_item5" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"codeSnippets", XVar.Array(),
"clickHandlerSnippets", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", true ) ),
"calcTotalsFor", 1,
"hasCharts", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "menu",
"type", "menu",
"layoutId", "topbar",
"disabled", false,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "menu-topbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "logo",
1, "menu" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "loginform_login",
1, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "welcome",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "welcome_item",
1, "welcome_item1",
2, "welcome_item2",
3, "welcome_item3",
4, "welcome_item4",
5, "welcome_item5" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"welcome_item", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.Branches",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.Branches",
"type", 6 ),
"linkIcon", new XVar( "glyph", "barcode",
"style", 0 ),
"linkComments", new XVar( "type", 0,
"text", "فهرست شعب و دسترسی مستقیم به تمامی اطلاعات یک شعبه" ),
"background", "#bc8f8f",
"linkType", 0 ),
"welcome_item1", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.OneForm_Fields",
"linkPage", "list",
"linkText", new XVar( "type", 0,
"text", "عناوین و سوالات" ),
"linkIcon", new XVar( "glyph", "send",
"style", 0 ),
"linkComments", new XVar( "type", 0,
"text", "فهرستی از سوالات و عناوین موجود در تمامی فرم ها" ),
"background", "#4169e1",
"linkType", 0 ),
"welcome_item2", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.OneForm_Fields_Groups",
"linkPage", "list",
"linkText", new XVar( "type", 0,
"text", "فرم ها و گروه سوالات" ),
"linkIcon", new XVar( "glyph", "flash",
"style", 0 ),
"linkComments", new XVar( "type", 0,
"text", "فرم ها و گروه های سوالات" ),
"background", "#d2691e",
"linkType", 0 ),
"welcome_item3", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.OneForm_Values",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.OneForm_Values",
"type", 6 ),
"linkIcon", new XVar( "glyph", "barcode",
"style", 0 ),
"linkComments", new XVar( "type", 0,
"text", "تمامی اطلاعات ثبت شده و پاسخ های سوالات" ),
"background", "#cd853f",
"linkType", 0 ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "logout_link",
1, "adminarea_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"welcome_item4", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.OneForm_Value_Files",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.OneForm_Value_Files",
"type", 6 ),
"linkIcon", new XVar( "glyph", "headphones" ),
"linkComments", new XVar( "text", "One Form Value Files description",
"type", 0 ),
"background", "#00c2c5",
"linkType", 0 ),
"welcome_item5", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.OneForm_Values_Images",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.OneForm_Values_Images",
"type", 6 ),
"linkIcon", new XVar( "glyph", "heart-empty" ),
"background", "#00c2c5",
"linkType", 0 ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"welcomePageStay", true,
"listTotals", 1,
"title", new XVar(  ) );
				}
			}
		}