
		// dbo.OneForm_Values
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_OneForm_Values_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "Branch",
1, "Field_ID",
2, "ShortText_Value",
3, "LongText_Value",
4, "Check_Value",
5, "Group_ID",
6, "Number_Value",
7, "RecordUser" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "Branch", new XVar( 0, "import_field1" ),
"Field_ID", new XVar( 0, "import_field2" ),
"ShortText_Value", new XVar( 0, "import_field3" ),
"LongText_Value", new XVar( 0, "import_field4" ),
"Check_Value", new XVar( 0, "import_field5" ),
"Group_ID", new XVar( 0, "import_field6" ),
"Number_Value", new XVar( 0, "import_field7" ),
"RecordUser", new XVar( 0, "import_field9" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field1",
1, "import_field2",
2, "import_field3",
3, "import_field4",
4, "import_field5",
5, "import_field6",
6, "import_field7",
7, "import_field9" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field9", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field1",
1, "import_field2",
2, "import_field3",
3, "import_field4",
4, "import_field5",
5, "import_field6",
6, "import_field7",
7, "import_field9" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"codeSnippets", XVar.Array(),
"clickHandlerSnippets", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1,
"hasCharts", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", false,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field1",
1, "import_field2",
2, "import_field3",
3, "import_field4",
4, "import_field5",
5, "import_field6",
6, "import_field7",
7, "import_field9" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field1", new XVar( "field", "Branch",
"type", "import_field" ),
"import_field2", new XVar( "field", "Field_ID",
"type", "import_field" ),
"import_field3", new XVar( "field", "ShortText_Value",
"type", "import_field" ),
"import_field4", new XVar( "field", "LongText_Value",
"type", "import_field" ),
"import_field5", new XVar( "field", "Check_Value",
"type", "import_field" ),
"import_field6", new XVar( "field", "Group_ID",
"type", "import_field" ),
"import_field7", new XVar( "field", "Number_Value",
"type", "import_field" ),
"import_field9", new XVar( "field", "RecordUser",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"title", new XVar(  ) );
				}
			}
		}