
		// dbo.OneForm_Values
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_OneForm_Values_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"details", new XVar( "dbo.OneForm_Values_Images", new XVar( "displayPreview", 1 ),
"dbo.OneForm_Value_Files", new XVar( "displayPreview", 1 ) ),
"master", new XVar( "dbo.Branches", new XVar( "preview", false ),
"dbo.OneForm_Fields", new XVar( "preview", false ),
"dbo.OneForm_Fields_Groups", new XVar( "preview", false ) ),
"fields", new XVar( "gridFields", new XVar( 0, "ID",
1, "Branch",
2, "Field_ID",
3, "ShortText_Value",
4, "LongText_Value",
5, "Check_Value",
6, "Group_ID",
7, "Number_Value",
8, "RecordDate",
9, "RecordUser" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "ID", new XVar( 0, "integrated_edit_field" ),
"Branch", new XVar( 0, "integrated_edit_field1" ),
"Field_ID", new XVar( 0, "integrated_edit_field2" ),
"ShortText_Value", new XVar( 0, "integrated_edit_field3" ),
"LongText_Value", new XVar( 0, "integrated_edit_field4" ),
"Check_Value", new XVar( 0, "integrated_edit_field5" ),
"Group_ID", new XVar( 0, "integrated_edit_field7" ),
"Number_Value", new XVar( 0, "integrated_edit_field8" ),
"RecordDate", new XVar( 0, "integrated_edit_field9" ),
"RecordUser", new XVar( 0, "integrated_edit_field10" ) ) ),
"pageLinks", new XVar( "edit", true,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close",
2, "prev",
3, "next",
4, "hamburger" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field7",
3, "integrated_edit_field2",
4, "integrated_edit_field8",
5, "integrated_edit_field3",
6, "integrated_edit_field5",
7, "integrated_edit_field4",
8, "integrated_edit_field9",
9, "integrated_edit_field10",
10, "details_preview",
11, "details_preview1" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"prev", "below-grid",
"next", "below-grid",
"hamburger", "below-grid",
"view_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field4", "grid",
"integrated_edit_field9", "grid",
"integrated_edit_field10", "grid",
"details_preview", "grid",
"details_preview1", "grid" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field9", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field10", new XVar( "location", "grid",
"cellId", "c4" ),
"details_preview", new XVar( "location", "grid",
"cellId", "c5" ),
"details_preview1", new XVar( "location", "grid",
"cellId", "c5" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"hamburger", new XVar( 0, "hamburger" ),
"view_edit", new XVar( 0, "view_edit" ),
"next", new XVar( 0, "next" ),
"prev", new XVar( 0, "prev" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field7",
7, "integrated_edit_field8",
8, "integrated_edit_field9",
9, "integrated_edit_field10" ),
"details_preview", new XVar( 0, "details_preview",
1, "details_preview1" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field7",
3, "integrated_edit_field2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field8",
1, "integrated_edit_field3",
2, "integrated_edit_field5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c4", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field4",
1, "integrated_edit_field9",
2, "integrated_edit_field10" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview",
1, "details_preview1" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 3,
"height", 2 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"codeSnippets", XVar.Array(),
"clickHandlerSnippets", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1,
"hasCharts", false ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", false,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "prev",
1, "next",
2, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c" ),
2, new XVar( "cell", "c4" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c5",
"colspan", 3 ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field7",
3, "integrated_edit_field2" ) ),
"c", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field8",
1, "integrated_edit_field3",
2, "integrated_edit_field5" ) ),
"c4", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field4",
1, "integrated_edit_field9",
2, "integrated_edit_field10" ) ),
"c5", new XVar( "model", "c3",
"items", new XVar( 0, "details_preview",
1, "details_preview1" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 3,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "view_edit" ) ),
"view_edit", new XVar( "type", "view_edit" ),
"next", new XVar( "type", "next" ),
"prev", new XVar( "type", "prev" ),
"integrated_edit_field", new XVar( "field", "ID",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field1", new XVar( "field", "Branch",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "Field_ID",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "ShortText_Value",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "LongText_Value",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field5", new XVar( "field", "Check_Value",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "Group_ID",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field8", new XVar( "field", "Number_Value",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field9", new XVar( "field", "RecordDate",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field10", new XVar( "field", "RecordUser",
"type", "integrated_edit_field",
"orientation", 0 ),
"details_preview", new XVar( "type", "details_preview",
"table", 22784,
"items", XVar.Array(),
"popup", false ),
"details_preview1", new XVar( "type", "details_preview",
"table", 22759,
"items", XVar.Array(),
"popup", false ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"title", new XVar(  ) );
				}
			}
		}