
		// dbo.OneForm_Values
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_OneForm_Values_edit
			{
				static public XVar options()
				{
					return new XVar( "details", new XVar( "dbo.OneForm_Values_Images", new XVar( "displayPreview", 2,
"previewPageId", "" ),
"dbo.OneForm_Value_Files", new XVar( "displayPreview", 2,
"previewPageId", "" ) ),
"master", new XVar( "dbo.Branches", new XVar( "preview", false ),
"dbo.OneForm_Fields", new XVar( "preview", false ),
"dbo.OneForm_Fields_Groups", new XVar( "preview", false ) ),
"captcha", new XVar( "captcha", false ),
"fields", new XVar( "gridFields", new XVar( 0, "Branch",
1, "Field_ID",
2, "Group_ID",
3, "Number_Value",
4, "ShortText_Value",
5, "LongText_Value",
6, "Check_Value" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"updateOnEditFields", new XVar( 0, "Field_ID",
1, "Group_ID",
2, "Number_Value",
3, "ShortText_Value",
4, "LongText_Value",
5, "Check_Value" ),
"fieldItems", new XVar( "Branch", new XVar( 0, "integrated_edit_field" ),
"Field_ID", new XVar( 0, "integrated_edit_field1" ),
"Group_ID", new XVar( 0, "integrated_edit_field6" ),
"Number_Value", new XVar( 0, "integrated_edit_field7" ),
"ShortText_Value", new XVar( 0, "integrated_edit_field2" ),
"LongText_Value", new XVar( 0, "integrated_edit_field3" ),
"Check_Value", new XVar( 0, "integrated_edit_field4" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", true,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "edit_message" ),
"below-grid", new XVar( 0, "edit_save",
1, "update_records",
2, "edit_back_list",
3, "edit_close",
4, "prev",
5, "next",
6, "hamburger" ),
"top", new XVar( 0, "edit_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field6",
2, "integrated_edit_field1",
3, "integrated_edit_field7",
4, "integrated_edit_field2",
5, "integrated_edit_field4",
6, "integrated_edit_field3" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "message_block" ) ),
"itemForms", new XVar( "edit_message", "above-grid",
"edit_save", "below-grid",
"update_records", "below-grid",
"edit_back_list", "below-grid",
"edit_close", "below-grid",
"prev", "below-grid",
"next", "below-grid",
"hamburger", "below-grid",
"edit_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field4", "grid",
"integrated_edit_field3", "grid" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c4" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "edit_header", new XVar( 0, "edit_header" ),
"hamburger", new XVar( 0, "hamburger" ),
"edit_reset", new XVar( 0, "edit_reset" ),
"edit_message", new XVar( 0, "edit_message" ),
"edit_save", new XVar( 0, "edit_save" ),
"edit_back_list", new XVar( 0, "edit_back_list" ),
"edit_close", new XVar( 0, "edit_close" ),
"edit_view", new XVar( 0, "edit_view" ),
"next", new XVar( 0, "next" ),
"prev", new XVar( 0, "prev" ),
"update_records", new XVar( 0, "update_records" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field6",
3, "integrated_edit_field7",
4, "integrated_edit_field2",
5, "integrated_edit_field3",
6, "integrated_edit_field4" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field6",
2, "integrated_edit_field1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field2",
2, "integrated_edit_field4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c4", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field3" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 3,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar( "update_records", new XVar( "tag", "UPDATE_N_RECORDS",
"type", 2 ) ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"codeSnippets", XVar.Array(),
"clickHandlerSnippets", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1,
"hasCharts", false ),
"misc", new XVar( "type", "edit",
"breadcrumb", false,
"nextPrev", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"edit", new XVar( "updateSelected", true ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "edit",
"type", "edit",
"layoutId", "nomenu",
"disabled", false,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "edit-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "edit_message" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "edit-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "edit_save",
1, "update_records",
2, "edit_back_list",
3, "edit_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "prev",
1, "next",
2, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "edit-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "edit_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c" ),
2, new XVar( "cell", "c4" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field6",
2, "integrated_edit_field1" ) ),
"c", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field2",
2, "integrated_edit_field4" ) ),
"c4", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field3" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 3,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "edit_header", new XVar( "type", "edit_header" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "edit_reset",
1, "edit_view" ) ),
"edit_reset", new XVar( "type", "edit_reset" ),
"edit_message", new XVar( "type", "edit_message" ),
"edit_save", new XVar( "type", "edit_save" ),
"edit_back_list", new XVar( "type", "edit_back_list" ),
"edit_close", new XVar( "type", "edit_close" ),
"edit_view", new XVar( "type", "edit_view" ),
"next", new XVar( "type", "next" ),
"prev", new XVar( "type", "prev" ),
"update_records", new XVar( "type", "update_records" ),
"integrated_edit_field", new XVar( "field", "Branch",
"type", "integrated_edit_field",
"updateOnEdit", false,
"orientation", 0 ),
"integrated_edit_field1", new XVar( "field", "Field_ID",
"type", "integrated_edit_field",
"updateOnEdit", true,
"orientation", 0 ),
"integrated_edit_field6", new XVar( "field", "Group_ID",
"type", "integrated_edit_field",
"updateOnEdit", true,
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "Number_Value",
"type", "integrated_edit_field",
"updateOnEdit", true,
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "ShortText_Value",
"type", "integrated_edit_field",
"updateOnEdit", true,
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "LongText_Value",
"type", "integrated_edit_field",
"updateOnEdit", true,
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "Check_Value",
"type", "integrated_edit_field",
"updateOnEdit", true,
"orientation", 0 ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"title", new XVar(  ) );
				}
			}
		}