
		// dbo.OneForm_Values
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_OneForm_Values_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", true,
"inlineEdit", false,
"spreadsheetMode", false,
"reorderRows", false,
"addToBottom", false,
"delete", true,
"updateSelected", true,
"addInPopup", true,
"editInPopup", true,
"viewInPopup", true,
"clickSort", true,
"sortDropdown", true,
"showHideFields", true,
"reorderFields", true,
"fieldFilter", true,
"hideNumberOfRecords", false ),
"master", new XVar( "dbo.Branches", new XVar( "preview", true ),
"dbo.OneForm_Fields", new XVar( "preview", true ),
"dbo.OneForm_Fields_Groups", new XVar( "preview", true ) ),
"listSearch", new XVar( "alwaysOnPanelFields", new XVar( 0, "Branch",
1, "Field_ID",
2, "Group_ID" ),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", true,
"searchSaving", true ),
"totals", new XVar( "ID", new XVar( "totalsType", "" ),
"Branch", new XVar( "totalsType", "" ),
"Field_ID", new XVar( "totalsType", "" ),
"ShortText_Value", new XVar( "totalsType", "" ),
"LongText_Value", new XVar( "totalsType", "" ),
"Check_Value", new XVar( "totalsType", "" ),
"File_Value", new XVar( "totalsType", "" ),
"Group_ID", new XVar( "totalsType", "" ),
"Number_Value", new XVar( "totalsType", "" ),
"RecordDate", new XVar( "totalsType", "" ),
"RecordUser", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "ID",
1, "Branch",
2, "Group_ID",
3, "Field_ID",
4, "ShortText_Value",
5, "LongText_Value",
6, "Check_Value",
7, "File_Value",
8, "Number_Value",
9, "RecordDate",
10, "RecordUser" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "Check_Value",
1, "ID",
2, "RecordUser",
3, "RecordDate",
4, "Number_Value",
5, "Group_ID",
6, "LongText_Value",
7, "ShortText_Value",
8, "Field_ID",
9, "Branch" ),
"filterFields", new XVar( 0, "Branch",
1, "Field_ID",
2, "Group_ID" ),
"inlineAddFields", new XVar( 0, "Branch",
1, "Group_ID",
2, "Field_ID",
3, "ShortText_Value",
4, "LongText_Value",
5, "Check_Value",
6, "File_Value",
7, "Number_Value" ),
"inlineEditFields", new XVar( 0, "Branch",
1, "Group_ID",
2, "Field_ID",
3, "ShortText_Value",
4, "LongText_Value",
5, "Check_Value",
6, "File_Value",
7, "Number_Value" ),
"fieldItems", new XVar( "ID", new XVar( 0, "simple_grid_field",
1, "simple_grid_field8" ),
"Branch", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field9" ),
"Group_ID", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field10" ),
"Field_ID", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field11" ),
"ShortText_Value", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field12" ),
"LongText_Value", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field13" ),
"Check_Value", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field14" ),
"File_Value", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field15" ),
"Number_Value", new XVar( 0, "grid_field",
1, "grid_field_label" ),
"RecordDate", new XVar( 0, "grid_field1",
1, "grid_field_label1" ),
"RecordUser", new XVar( 0, "grid_field2",
1, "grid_field_label2" ) ),
"hideEmptyFields", new XVar( 0, "ShortText_Value",
1, "LongText_Value",
2, "File_Value",
3, "Number_Value" ),
"fieldFilterFields", new XVar( 0, "ID",
1, "Branch",
2, "Group_ID",
3, "Field_ID",
4, "ShortText_Value",
5, "LongText_Value",
6, "Check_Value",
7, "File_Value" ) ),
"pageLinks", new XVar( "edit", true,
"add", true,
"view", true,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "add",
1, "inline_add",
2, "delete",
3, "update_selected",
4, "details_found",
5, "page_size",
6, "print_panel",
7, "columns_control",
8, "sort_dropdown" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel",
4, "filter_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search_field",
4, "simple_search_option",
5, "simple_search",
6, "list_options",
7, "loginform_login",
8, "username_button" ),
"top", new XVar( 0, "master_info" ),
"grid", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field",
2, "simple_grid_field9",
3, "simple_grid_field1",
4, "simple_grid_field10",
5, "simple_grid_field7",
6, "simple_grid_field11",
7, "simple_grid_field2",
8, "simple_grid_field12",
9, "simple_grid_field3",
10, "simple_grid_field13",
11, "simple_grid_field4",
12, "simple_grid_field14",
13, "simple_grid_field5",
14, "simple_grid_field15",
15, "simple_grid_field6",
16, "grid_checkbox_head",
17, "grid_checkbox",
18, "grid_edit",
19, "grid_inline_cancel",
20, "grid_copy",
21, "grid_view",
22, "grid_field_label",
23, "grid_field",
24, "grid_field_label1",
25, "grid_field1",
26, "grid_field_label2",
27, "grid_field2" ) ),
"formXtTags", new XVar( "below-grid", new XVar( 0, "pagination" ),
"top", new XVar( 0, "mastertable_block" ) ),
"itemForms", new XVar( "add", "above-grid",
"inline_add", "above-grid",
"delete", "above-grid",
"update_selected", "above-grid",
"details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"columns_control", "above-grid",
"sort_dropdown", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"filter_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search_field", "supertop",
"simple_search_option", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"master_info", "top",
"simple_grid_field8", "grid",
"simple_grid_field", "grid",
"simple_grid_field9", "grid",
"simple_grid_field1", "grid",
"simple_grid_field10", "grid",
"simple_grid_field7", "grid",
"simple_grid_field11", "grid",
"simple_grid_field2", "grid",
"simple_grid_field12", "grid",
"simple_grid_field3", "grid",
"simple_grid_field13", "grid",
"simple_grid_field4", "grid",
"simple_grid_field14", "grid",
"simple_grid_field5", "grid",
"simple_grid_field15", "grid",
"simple_grid_field6", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"grid_edit", "grid",
"grid_inline_cancel", "grid",
"grid_copy", "grid",
"grid_view", "grid",
"grid_field_label", "grid",
"grid_field", "grid",
"grid_field_label1", "grid",
"grid_field1", "grid",
"grid_field_label2", "grid",
"grid_field2", "grid" ),
"itemLocations", new XVar( "simple_grid_field8", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"grid_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_copy", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_view", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_field_label", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"grid_field", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"grid_field_label1", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"grid_field1", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"grid_field_label2", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"grid_field2", new XVar( "location", "grid",
"cellId", "cell_field10" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"details_found", new XVar( 0, "details_found" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field1",
1, "search_panel_field2",
2, "search_panel_field3",
3, "search_panel_field4",
4, "search_panel_field5",
5, "search_panel_field",
6, "search_panel_field6",
7, "search_panel_field7",
8, "search_panel_field8",
9, "search_panel_field9" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"add", new XVar( 0, "add" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2",
3, "-3",
4, "-4",
5, "-5",
6, "-6" ),
"export_selected", new XVar( 0, "export_selected" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"delete", new XVar( 0, "delete" ),
"delete_selected", new XVar( 0, "delete_selected" ),
"master_info", new XVar( 0, "master_info" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"filter_panel", new XVar( 0, "filter_panel" ),
"filter_panel_field", new XVar( 0, "filter_panel_field",
1, "filter_panel_field1",
2, "filter_panel_field2" ),
"import", new XVar( 0, "import" ),
"simple_search_field", new XVar( 0, "simple_search_field" ),
"simple_search_option", new XVar( 0, "simple_search_option" ),
"sort_dropdown", new XVar( 0, "sort_dropdown" ),
"save_search", new XVar( 0, "save_search" ),
"saved_searches", new XVar( 0, "saved_searches" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field7",
3, "simple_grid_field2",
4, "simple_grid_field3",
5, "simple_grid_field4",
6, "simple_grid_field5",
7, "simple_grid_field6",
8, "grid_field",
9, "grid_field1",
10, "grid_field2" ),
"grid_field_label", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field9",
2, "simple_grid_field10",
3, "simple_grid_field11",
4, "simple_grid_field12",
5, "simple_grid_field13",
6, "simple_grid_field14",
7, "simple_grid_field15",
8, "grid_field_label",
9, "grid_field_label1",
10, "grid_field_label2" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"grid_edit", new XVar( 0, "grid_edit" ),
"grid_view", new XVar( 0, "grid_view" ),
"update_selected", new XVar( 0, "update_selected" ),
"columns_control", new XVar( 0, "columns_control" ),
"grid_copy", new XVar( 0, "grid_copy" ),
"expand_button", new XVar( 0, "expand_button" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ID_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Branch_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Group_ID_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Field_ID_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ShortText_Value_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "LongText_Value_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Check_Value_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "File_Value_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Number_Value_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "RecordDate_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "RecordUser_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "edit_column",
1, "inline_cancel",
2, "copy_column",
3, "view_column" ),
"items", new XVar( 0, "grid_edit",
1, "grid_inline_cancel",
2, "grid_copy",
3, "grid_view" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ID_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Branch_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Group_ID_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Field_ID_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ShortText_Value_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "LongText_Value_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Check_Value_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "File_Value_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Number_Value_fieldcolumn" ),
"items", new XVar( 0, "grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "RecordDate_fieldcolumn" ),
"items", new XVar( 0, "grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "RecordUser_fieldcolumn" ),
"items", new XVar( 0, "grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 13,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"codeSnippets", XVar.Array(),
"clickHandlerSnippets", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1,
"hasCharts", false ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", false,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c4" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add",
1, "inline_add",
2, "delete",
3, "update_selected" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel",
3, "columns_control" ) ),
"c3", new XVar( "model", "c3",
"items", XVar.Array() ),
"c4", new XVar( "model", "c4",
"items", new XVar( 0, "sort_dropdown" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel",
2, "filter_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search_field",
1, "simple_search_option",
2, "simple_search",
3, "list_options",
4, "loginform_login",
5, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_checkbox" ),
2, new XVar( "cell", "headcell_field" ),
3, new XVar( "cell", "headcell_field1" ),
4, new XVar( "cell", "headcell_field2" ),
5, new XVar( "cell", "headcell_field3" ),
6, new XVar( "cell", "headcell_field4" ),
7, new XVar( "cell", "headcell_field5" ),
8, new XVar( "cell", "headcell_field6" ),
9, new XVar( "cell", "headcell_field7" ),
10, new XVar( "cell", "headcell_field8" ),
11, new XVar( "cell", "headcell_field9" ),
12, new XVar( "cell", "headcell_field10" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_checkbox" ),
2, new XVar( "cell", "cell_field" ),
3, new XVar( "cell", "cell_field1" ),
4, new XVar( "cell", "cell_field2" ),
5, new XVar( "cell", "cell_field3" ),
6, new XVar( "cell", "cell_field4" ),
7, new XVar( "cell", "cell_field5" ),
8, new XVar( "cell", "cell_field6" ),
9, new XVar( "cell", "cell_field7" ),
10, new XVar( "cell", "cell_field8" ),
11, new XVar( "cell", "cell_field9" ),
12, new XVar( "cell", "cell_field10" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_checkbox" ),
2, new XVar( "cell", "footcell_field" ),
3, new XVar( "cell", "footcell_field1" ),
4, new XVar( "cell", "footcell_field2" ),
5, new XVar( "cell", "footcell_field3" ),
6, new XVar( "cell", "footcell_field4" ),
7, new XVar( "cell", "footcell_field5" ),
8, new XVar( "cell", "footcell_field6" ),
9, new XVar( "cell", "footcell_field7" ),
10, new XVar( "cell", "footcell_field8" ),
11, new XVar( "cell", "footcell_field9" ),
12, new XVar( "cell", "footcell_field10" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "ID",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "ID",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "Branch",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "Branch",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "Group_ID",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "Group_ID",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "Field_ID",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "Field_ID",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "ShortText_Value",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "ShortText_Value",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "LongText_Value",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "LongText_Value",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "Check_Value",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "Check_Value",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "File_Value",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "File_Value",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_edit",
1, "grid_inline_cancel",
2, "grid_copy",
3, "grid_view" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label" ),
"field", "Number_Value",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field" ),
"field", "Number_Value",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label1" ),
"field", "RecordDate",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field1" ),
"field", "RecordDate",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label2" ),
"field", "RecordUser",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field2" ),
"field", "RecordUser",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"details_found", new XVar( "type", "details_found" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field5",
1, "search_panel_field9",
2, "search_panel_field8",
3, "search_panel_field7",
4, "search_panel_field6",
5, "search_panel_field",
6, "search_panel_field4",
7, "search_panel_field3",
8, "search_panel_field2",
9, "search_panel_field1" ),
"_flexiblePanel", true ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "export_selected",
1, "delete_selected",
2, "-6",
3, "advsearch_link",
4, "-1",
5, "show_search_panel",
6, "hide_search_panel",
7, "-4",
8, "save_search",
9, "-5",
10, "saved_searches",
11, "-",
12, "export",
13, "-3",
14, "import" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field1", new XVar( "field", "Branch",
"type", "search_panel_field",
"alwaysOnPanel", true,
"required", false ),
"search_panel_field2", new XVar( "field", "Field_ID",
"type", "search_panel_field",
"alwaysOnPanel", true,
"required", false ),
"search_panel_field3", new XVar( "field", "ShortText_Value",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"search_panel_field4", new XVar( "field", "LongText_Value",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"search_panel_field5", new XVar( "field", "Check_Value",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"add", new XVar( "type", "add",
"popup", true ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"export_selected", new XVar( "type", "export_selected" ),
"-1", new XVar( "type", "-" ),
"-2", new XVar( "type", "-" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_records",
2, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"delete", new XVar( "type", "delete" ),
"delete_selected", new XVar( "type", "delete_selected" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "22276", "true",
"22321", "true",
"22348", "true" ) ),
"search_panel_field", new XVar( "field", "Group_ID",
"type", "search_panel_field",
"alwaysOnPanel", true,
"required", false ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "logout_link",
1, "adminarea_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"filter_panel", new XVar( "type", "filter_panel",
"items", new XVar( 0, "filter_panel_field",
1, "filter_panel_field2",
2, "filter_panel_field1" ) ),
"filter_panel_field", new XVar( "field", "Branch",
"type", "filter_panel_field" ),
"import", new XVar( "type", "import" ),
"-3", new XVar( "type", "-" ),
"simple_search_field", new XVar( "type", "simple_search_field" ),
"simple_search_option", new XVar( "type", "simple_search_option" ),
"sort_dropdown", new XVar( "type", "sort_dropdown" ),
"save_search", new XVar( "type", "save_search" ),
"-4", new XVar( "type", "-" ),
"saved_searches", new XVar( "type", "saved_searches" ),
"-5", new XVar( "type", "-" ),
"filter_panel_field1", new XVar( "field", "Field_ID",
"type", "filter_panel_field" ),
"filter_panel_field2", new XVar( "field", "Group_ID",
"type", "filter_panel_field" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-6", new XVar( "type", "-" ),
"simple_grid_field", new XVar( "field", "ID",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false,
"clickSort", true,
"showFilter", true ),
"simple_grid_field8", new XVar( "type", "grid_field_label",
"field", "ID",
"clickSort", true,
"showFilter", true ),
"simple_grid_field1", new XVar( "field", "Branch",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true ),
"simple_grid_field9", new XVar( "type", "grid_field_label",
"field", "Branch",
"clickSort", true,
"showFilter", true ),
"simple_grid_field7", new XVar( "field", "Group_ID",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true ),
"simple_grid_field10", new XVar( "type", "grid_field_label",
"field", "Group_ID",
"clickSort", true,
"showFilter", true ),
"simple_grid_field2", new XVar( "field", "Field_ID",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true ),
"simple_grid_field11", new XVar( "type", "grid_field_label",
"field", "Field_ID",
"clickSort", true,
"showFilter", true ),
"simple_grid_field3", new XVar( "field", "ShortText_Value",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true,
"hideEmpty", true ),
"simple_grid_field12", new XVar( "type", "grid_field_label",
"field", "ShortText_Value",
"clickSort", true,
"showFilter", true ),
"simple_grid_field4", new XVar( "field", "LongText_Value",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true,
"hideEmpty", true ),
"simple_grid_field13", new XVar( "type", "grid_field_label",
"field", "LongText_Value",
"clickSort", true,
"showFilter", true ),
"simple_grid_field5", new XVar( "field", "Check_Value",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true,
"hideEmpty", false ),
"simple_grid_field14", new XVar( "type", "grid_field_label",
"field", "Check_Value",
"clickSort", true,
"showFilter", true ),
"simple_grid_field6", new XVar( "field", "File_Value",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"clickSort", true,
"showFilter", true,
"hideEmpty", true ),
"simple_grid_field15", new XVar( "type", "grid_field_label",
"field", "File_Value",
"clickSort", true,
"showFilter", true ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"grid_edit", new XVar( "type", "grid_edit",
"popup", true ),
"grid_view", new XVar( "type", "grid_view",
"popup", true ),
"grid_field", new XVar( "field", "Number_Value",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true,
"hideEmpty", true ),
"grid_field_label", new XVar( "type", "grid_field_label",
"field", "Number_Value",
"clickSort", true ),
"grid_field1", new XVar( "field", "RecordDate",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label1", new XVar( "type", "grid_field_label",
"field", "RecordDate",
"clickSort", true ),
"grid_field2", new XVar( "field", "RecordUser",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label2", new XVar( "type", "grid_field_label",
"field", "RecordUser",
"clickSort", true ),
"search_panel_field6", new XVar( "field", "Number_Value",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"search_panel_field7", new XVar( "field", "RecordDate",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"search_panel_field8", new XVar( "field", "RecordUser",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"update_selected", new XVar( "type", "update_selected",
"popup", true ),
"columns_control", new XVar( "type", "columns_control",
"reorder", true,
"showHide", true ),
"grid_copy", new XVar( "type", "grid_copy",
"popup", true ),
"search_panel_field9", new XVar( "field", "ID",
"type", "search_panel_field" ),
"expand_button", new XVar( "type", "expand_button" ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"autoAddNewRecord", true,
"version", 13,
"pageWidth", "full",
"reorderRows", false,
"reorderRowsField", "",
"addToBottom", false,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"title", new XVar(  ) );
				}
			}
		}