using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void menu_main()
		{
			GlobalVars.runnerMenus.InitAndSetArrayItem(new XVar( "name", "main",
"id", "main",
"treeLike", true,
"root", new XVar( "id", "",
"parent", "",
"children", new XVar( 0, new XVar( "id", "1",
"parent", "",
"children", XVar.Array(),
"data", new XVar( "name", new XVar( "table", "dbo.Branches",
"type", 6 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 2,
"linkType", 0,
"openType", 0,
"iconType", 2,
"iconName", "glyphicon-barcode",
"iconStyle", 0,
"showIconType", 2,
"linkToAnotherApp", false,
"table", 22276,
"pageType", "list" ) ),
1, new XVar( "id", "3",
"parent", "",
"children", XVar.Array(),
"data", new XVar( "name", new XVar( "table", "dbo.OneForm_Fields_Groups",
"type", 6 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 2,
"linkType", 0,
"openType", 0,
"iconType", 2,
"iconName", "glyphicon-flash",
"iconStyle", 0,
"showIconType", 2,
"linkToAnotherApp", false,
"table", 22348,
"pageType", "list" ) ),
2, new XVar( "id", "2",
"parent", "",
"children", XVar.Array(),
"data", new XVar( "name", new XVar( "table", "dbo.OneForm_Fields",
"type", 6 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 2,
"linkType", 0,
"openType", 0,
"iconType", 2,
"iconName", "glyphicon-send",
"iconStyle", 0,
"showIconType", 2,
"linkToAnotherApp", false,
"table", 22321,
"pageType", "list" ) ),
3, new XVar( "id", "4",
"parent", "",
"children", XVar.Array(),
"data", new XVar( "name", new XVar( "table", "dbo.OneForm_Values",
"type", 6 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 2,
"linkType", 0,
"openType", 0,
"iconType", 2,
"iconName", "glyphicon-barcode",
"iconStyle", 0,
"showIconType", 2,
"linkToAnotherApp", false,
"table", 22369,
"pageType", "list" ) ),
4, new XVar( "id", "5",
"parent", "",
"children", XVar.Array(),
"data", new XVar( "name", new XVar( "table", "dbo.OneForm_Value_Files",
"type", 6 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 2,
"linkType", 0,
"openType", 0,
"iconType", 2,
"iconName", "glyphicon-headphones",
"iconStyle", 0,
"showIconType", 2,
"linkToAnotherApp", false,
"table", 22759,
"pageType", "list" ) ),
5, new XVar( "id", "6",
"parent", "",
"children", XVar.Array(),
"data", new XVar( "name", new XVar( "table", "dbo.OneForm_Values_Images",
"type", 6 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 2,
"linkType", 0,
"openType", 0,
"iconType", 2,
"iconName", "glyphicon-heart-empty",
"iconStyle", 0,
"showIconType", 2,
"linkToAnotherApp", false,
"table", 22784,
"pageType", "list" ) ) ),
"data", new XVar( "name", new XVar( "text", "",
"type", 0 ),
"comments", new XVar( "text", "",
"type", 0 ),
"style", "",
"href", "",
"params", "",
"pageId", "",
"itemType", 0,
"linkType", 2,
"openType", 0,
"iconType", 0,
"iconName", "",
"iconStyle", 0,
"showIconType", 1,
"linkToAnotherApp", false ) ) ), "main");
		}
	}

}
