using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void Apply()
		{
			GlobalVars.runnerProjectSettings = new XVar(new XVar( "createRestAPI", true,
"restAPIReturnEncodedBinary", true,
"restAPIAcceptEncodedBinary", true,
"restAPIAuthType", "basic",
"landingSettings", new XVar( "type", 1,
"table", "<global>",
"pageId", "menu",
"page", "menu",
"url", "/menu?page=menu" ),
"menuIds", new XVar( 0, "main",
1, "adminarea" ),
"tablesAdvSecurity", new XVar( "dbo.Branches", new XVar( "table", 22276 ),
"dbo.OneForm_Fields", new XVar( "table", 22321 ),
"dbo.OneForm_Fields_Groups", new XVar( "table", 22348 ),
"dbo.OneForm_Values", new XVar( "advSecurity", 2,
"table", 22369 ),
"dbo.OneForm_Value_Files", new XVar( "table", 22759 ),
"dbo.OneForm_Values_Images", new XVar( "table", 22784 ) ),
"customTemplates", new XVar( 0, "header" ),
"hasCustomCss", true,
"phpSpreadsheet", false,
"ext", "aspx",
"security", new XVar( "projectName", "",
"loginDataSource", "",
"loginForm", 0,
"dynamicPermissions", true,
"dpTablePrefix", "dbo.OneForm_",
"dpTableConnId", "conn",
"providers", new XVar( 0, new XVar( "useAdGroups", true,
"type", "%ad",
"name", "ad",
"active", true,
"label", new XVar( "text", "Active Directory",
"type", 0 ),
"code", "ad",
"url", "LDAP://10.7.1.10",
"domain", "FRS.Local",
"baseDN", "DC=FRS,DC=Local",
"loginAutomatically", false,
"admins", new XVar( 0, "sh-sadeghi",
1, "DCManager" ) ) ),
"enabled", true,
"advancedSecurityAvailable", true,
"userGroupsAvailable", true,
"hardcodedLogin", false,
"defaultProviderCode", "ad",
"adOnlyLogin", true,
"sessionControl", new XVar( "lifeTime", 15,
"sessionName", "vPPX1C7gQscIdNCT4WwU",
"JWTSecret", "WqPmeH3GbOueSoeo7Z3u",
"keepAlive", true,
"forceExpire", false ),
"registration", new XVar( "remindMethod", 0,
"hashAlgorithm", 0,
"caseInsensitiveLogin", true,
"passwordValidation", new XVar( "strong", false,
"minimumLength", 8,
"uniqueCharacters", 4,
"digitsAndSymbols", 2,
"upperAndLowerCase", false ),
"registerPage", false ),
"captchaSettings", new XVar( "captchaType", 0,
"siteKey", "",
"secretKey", "",
"passesCount", 5 ),
"emailSettings", new XVar( "fromEmail", "",
"usePHPDefinedSMTP", false,
"useBuiltInMailer", false,
"SMTPServer", "localhost",
"SMTPPort", 25,
"SMTPUser", "",
"SMTPPassword", "",
"securityProtocol", 0 ),
"advancedSecurity", new XVar( "allowGuestLogin", true ),
"auditAndLocking", new XVar( "loggingMode", 1,
"loggingTable", new XVar( "connId", "conn",
"table", "dbo.HWFlow_SQL2019_audit" ),
"loggingFile", "audit.log",
"logSecurityActions", true,
"lockAfterUnsuccessfulLogin", false,
"enableLocking", true,
"lockingTable", new XVar( "connId", "conn",
"table", "dbo.Oneform_locking" ),
"tables", new XVar( "dbo.Branches", new XVar(  ),
"dbo.OneForm_Fields", new XVar( "logModifications", true,
"logFieldValues", true,
"recordLocking", true ),
"dbo.OneForm_Fields_Groups", new XVar( "logModifications", true,
"logFieldValues", true,
"recordLocking", true ),
"dbo.OneForm_Values", new XVar( "logModifications", true,
"logFieldValues", true,
"recordLocking", true ) ) ),
"twoFactorSettings", new XVar( "available", false,
"required", false,
"enable", true,
"remember", true,
"types", new XVar(  ),
"twoFactorField", "",
"emailField", "",
"phoneField", "",
"codeField", "",
"projectName", "" ),
"staticPermissions", new XVar( "groups", new XVar( "<Default>", new XVar( "permissions", new XVar( "dbo.Branches", new XVar( "mask", "ADESPI",
"table", "dbo.Branches",
"restrictedPages", new XVar(  ) ),
"dbo.OneForm_Fields", new XVar( "mask", "ADESPI",
"table", "dbo.OneForm_Fields",
"restrictedPages", new XVar(  ) ),
"dbo.OneForm_Fields_Groups", new XVar( "mask", "ADESPI",
"table", "dbo.OneForm_Fields_Groups",
"restrictedPages", new XVar(  ) ),
"dbo.OneForm_Values", new XVar( "mask", "ADESPI",
"table", "dbo.OneForm_Values",
"restrictedPages", new XVar(  ) ),
"<global>", new XVar( "mask", "ADESPI",
"table", "<global>",
"restrictedPages", new XVar(  ) ) ),
"admin", false,
"username", "<Default>" ),
"<Guest>", new XVar( "permissions", new XVar( "dbo.Branches", new XVar( "mask", "S",
"table", "dbo.Branches",
"restrictedPages", new XVar(  ) ),
"dbo.OneForm_Fields", new XVar( "mask", "S",
"table", "dbo.OneForm_Fields",
"restrictedPages", new XVar(  ) ),
"dbo.OneForm_Fields_Groups", new XVar( "mask", "S",
"table", "dbo.OneForm_Fields_Groups",
"restrictedPages", new XVar(  ) ),
"dbo.OneForm_Values", new XVar( "mask", "S",
"table", "dbo.OneForm_Values",
"restrictedPages", new XVar(  ) ),
"<global>", new XVar( "mask", "S",
"table", "<global>",
"restrictedPages", new XVar(  ) ) ) ) ) ),
"adAdminGroups", XVar.Array(),
"showUserSource", false,
"dbProviderCodes", XVar.Array() ),
"notifications", new XVar( "enabled", false,
"table", new XVar( "connId", "",
"table", "" ) ),
"allTables", new XVar( "dbo.Branches", new XVar( "gid", 22276,
"name", "dbo.Branches",
"shortName", "Branches",
"type", 0,
"caption", new XVar( "English", "Branches",
"Farsi", "شعب" ),
"connId", "conn",
"color", "bc8f8f",
"originalTable", "dbo.Branches" ),
"dbo.OneForm_Fields", new XVar( "gid", 22321,
"name", "dbo.OneForm_Fields",
"shortName", "OneForm_Fields",
"type", 0,
"caption", new XVar( "English", "One Form Fields",
"Farsi", "عناوین فرم" ),
"connId", "conn",
"color", "4169e1",
"originalTable", "dbo.OneForm_Fields" ),
"dbo.OneForm_Fields_Groups", new XVar( "gid", 22348,
"name", "dbo.OneForm_Fields_Groups",
"shortName", "OneForm_Fields_Groups",
"type", 0,
"caption", new XVar( "English", "One Form Fields Groups",
"Farsi", "فرم ها" ),
"connId", "conn",
"color", "d2691e",
"originalTable", "dbo.OneForm_Fields_Groups" ),
"dbo.OneForm_Values", new XVar( "gid", 22369,
"name", "dbo.OneForm_Values",
"shortName", "OneForm_Values",
"type", 0,
"caption", new XVar( "English", "One Form Values",
"Farsi", "اطلاعات" ),
"connId", "conn",
"color", "cd853f",
"originalTable", "dbo.OneForm_Values" ),
"dbo.OneForm_Value_Files", new XVar( "gid", 22759,
"name", "dbo.OneForm_Value_Files",
"shortName", "OneForm_Value_Files",
"type", 0,
"caption", new XVar( "Farsi", "فایل ها" ),
"connId", "conn",
"color", "00c2c5",
"originalTable", "dbo.OneForm_Value_Files" ),
"dbo.OneForm_Values_Images", new XVar( "gid", 22784,
"name", "dbo.OneForm_Values_Images",
"shortName", "OneForm_Values_Images",
"type", 0,
"caption", new XVar( "Farsi", "تصاویر" ),
"connId", "conn",
"color", "00c2c5",
"originalTable", "dbo.OneForm_Values_Images" ) ),
"tablesByShort", new XVar( "Branches", "dbo.Branches",
"OneForm_Fields", "dbo.OneForm_Fields",
"OneForm_Fields_Groups", "dbo.OneForm_Fields_Groups",
"OneForm_Values", "dbo.OneForm_Values",
"OneForm_Value_Files", "dbo.OneForm_Value_Files",
"OneForm_Values_Images", "dbo.OneForm_Values_Images" ),
"tablesByGood", new XVar( "dbo_Branches", "dbo.Branches",
"dbo_OneForm_Fields", "dbo.OneForm_Fields",
"dbo_OneForm_Fields_Groups", "dbo.OneForm_Fields_Groups",
"dbo_OneForm_Values", "dbo.OneForm_Values",
"dbo_OneForm_Value_Files", "dbo.OneForm_Value_Files",
"dbo_OneForm_Values_Images", "dbo.OneForm_Values_Images" ),
"events", new XVar( 0, new XVar( "gid", 22751,
"type", "EVENT_FIELD",
"name", "Event" ) ),
"languages", new XVar( 0, new XVar( "name", "Farsi",
"nativeName", "فارسى",
"rtl", true,
"filename", "Farsi.lng" ) ),
"languageNames", new XVar( 0, "Farsi" ),
"defaultLanguage", "Farsi",
"detectDefaultLanguage", true,
"charset", "utf-8",
"codepage", 65001,
"defaultConnID", "conn",
"wrConnectionID", "",
"settingsTable", new XVar( "connId", "conn",
"table", "dbo.OneForm2_settings" ),
"wizardBuild", "43785",
"projectBuild", "iOcsjfFQnyqV",
"projectTheme", "cerulean",
"projectSize", "small",
"customErrorMsg", new XVar( "text", "Error occured.",
"type", 0 ),
"cloudSettings", new XVar( "cloudAmazonRegion", "",
"cloudAmazonBucket", "",
"cloudAmazonAccessKey", "",
"cloudAmazonSecretKey", "",
"cloudWasabiRegion", "",
"cloudWasabiBucket", "",
"cloudWasabiAccessKey", "",
"cloudWasabiSecretKey", "",
"cloudGDriveClientId", "",
"cloudGDriveClientSecret", "",
"cloudOneDriveClientId", "",
"cloudOneDriveClientSecret", "",
"cloudOneDriveDrive", "",
"cloudOneDriveAccountType", 0,
"cloudOneDriveDirectoryId", "",
"cloudDropboxClientId", "",
"cloudDropboxClientSecret", "" ),
"mapSettings", new XVar( "embed", true,
"provider", 0,
"apikey", "" ),
"viewPluginsWithJS", XVar.Array(),
"rtlLanguages", new XVar( "Farsi", true ),
"smsSettings", new XVar( "smsProvider", 4,
"iBusername", "",
"iBpassword", "",
"iBsender", "",
"essUsername", "",
"essPassword", "",
"essSender", "",
"gwApiToken", "",
"gwSender", "",
"mbAuth", "",
"mbSender", "",
"twilioSID", "",
"twilioAuth", "",
"twilioNumber", "",
"phoneField", "",
"counryCode", "+1",
"wauUsername", "",
"wauPassword", "",
"wauSender", "" ) ));
		}
	}

}
