using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void table_OneForm_Values()
		{
			GlobalVars.runnerTableSettings.InitAndSetArrayItem(new XVar( "name", "dbo.OneForm_Values",
"shortName", "OneForm_Values",
"advancedSecurityType", 2,
"pagesByType", new XVar( "add", new XVar( 0, "add" ),
"export", new XVar( 0, "export" ),
"import", new XVar( 0, "import" ),
"edit", new XVar( 0, "edit" ),
"view", new XVar( 0, "view" ),
"list", new XVar( 0, "list" ),
"print", new XVar( 0, "print" ),
"search", new XVar( 0, "search" ) ),
"pageTypes", new XVar( "add", "add",
"export", "export",
"import", "import",
"edit", "edit",
"view", "view",
"list", "list",
"print", "print",
"search", "search" ),
"defaultPages", new XVar( "add", "add",
"export", "export",
"import", "import",
"edit", "edit",
"view", "view",
"list", "list",
"print", "print",
"search", "search" ),
"tableOwnerIdField", "RecordUser",
"audit", true,
"locking", true,
"afterEditDetails", "dbo.OneForm_Values",
"afterAddDetail", "dbo.OneForm_Values",
"detailsBadgeColor", "cd853f",
"pageSizeRecords", 10,
"pageSizeSelectorRecords", new XVar( 0, "10",
1, "20",
2, "30",
3, "50",
4, "100",
5, "150",
6, "500",
7, "all" ),
"resizeColumns", true,
"warnLeavingEdit", true,
"orderInfo", new XVar( 0, new XVar( "index", 1,
"dir", "DESC",
"field", "ID" ) ),
"sql", "SELECT\n	ID,\n	Branch,\n	Group_ID,\n	Field_ID,\n	Number_Value,\n	ShortText_Value,\n	LongText_Value,\n	Check_Value,\n	File_Value,\n	RecordDate,\n	RecordUser\nFROM\n	dbo.OneForm_Values\nORDER BY\n	ID DESC\n",
"keyFields", new XVar( 0, "ID" ),
"deviceHideFields", new XVar( "1", XVar.Array(),
"5", XVar.Array() ),
"fields", new XVar( "ID", new XVar( "name", "ID",
"goodName", "ID",
"strField", "ID",
"index", 1,
"type", 3,
"autoinc", true,
"sqlExpression", "ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Values" ),
"Branch", new XVar( "name", "Branch",
"goodName", "Branch",
"strField", "Branch",
"index", 2,
"type", 2,
"sqlExpression", "Branch",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Lookup wizard",
"required", true,
"lookupType", 2,
"lookupTable", "dbo.Branches",
"lookupTableConnection", "conn",
"lookupLinkField", "Code",
"lookupDisplayField", "CAST([Code] AS NVARCHAR(4)) + '-' + BrName",
"lookupCustomDisplay", true,
"lookupOrderBy", "Code" ) ),
"filterFormat", new XVar( "format", "Values list" ),
"tableName", "dbo.OneForm_Values" ),
"Field_ID", new XVar( "name", "Field_ID",
"goodName", "Field_ID",
"strField", "Field_ID",
"index", 4,
"type", 2,
"sqlExpression", "Field_ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Lookup wizard",
"lookupType", 2,
"lookupTable", "dbo.OneForm_Fields",
"lookupTableConnection", "conn",
"lookupLinkField", "ID",
"lookupDisplayField", "CAST([ID] as NVARCHAR(5)) + '-' +FieldTitle",
"lookupCustomDisplay", true,
"lookupOrderBy", "ID",
"lookupDependent", true,
"lookupDependentFields", new XVar( 0, new XVar( "masterField", "Group_ID",
"lookupField", "Group_ID" ) ),
"fieldEvents", new XVar( 0, new XVar( "event", "change",
"handlerId", 22751 ) ) ) ),
"tableName", "dbo.OneForm_Values" ),
"ShortText_Value", new XVar( "name", "ShortText_Value",
"goodName", "ShortText_Value",
"strField", "ShortText_Value",
"index", 6,
"type", 202,
"sqlExpression", "ShortText_Value",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Values" ),
"LongText_Value", new XVar( "name", "LongText_Value",
"goodName", "LongText_Value",
"strField", "LongText_Value",
"index", 7,
"type", 202,
"sqlExpression", "LongText_Value",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Text area" ) ),
"tableName", "dbo.OneForm_Values" ),
"Check_Value", new XVar( "name", "Check_Value",
"goodName", "Check_Value",
"strField", "Check_Value",
"index", 8,
"type", 11,
"sqlExpression", "Check_Value",
"viewFormats", new XVar( "view", new XVar( "format", "Checkbox" ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Checkbox" ) ),
"tableName", "dbo.OneForm_Values" ),
"File_Value", new XVar( "name", "File_Value",
"goodName", "File_Value",
"strField", "File_Value",
"index", 9,
"type", 204,
"sqlExpression", "File_Value",
"viewFormats", new XVar( "view", new XVar( "format", "Database Image",
"imageCaptions", 1 ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Database image" ) ),
"tableName", "dbo.OneForm_Values" ),
"Group_ID", new XVar( "name", "Group_ID",
"goodName", "Group_ID",
"strField", "Group_ID",
"index", 3,
"type", 2,
"sqlExpression", "Group_ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Lookup wizard",
"required", true,
"lookupType", 2,
"lookupTable", "dbo.OneForm_Fields_Groups",
"lookupTableConnection", "conn",
"lookupLinkField", "ID",
"lookupDisplayField", "CAST([ID] as NVARCHAR(5)) + '-' +Group_Name",
"lookupCustomDisplay", true,
"lookupOrderBy", "ID" ) ),
"tableName", "dbo.OneForm_Values" ),
"Number_Value", new XVar( "name", "Number_Value",
"goodName", "Number_Value",
"strField", "Number_Value",
"index", 5,
"type", 202,
"sqlExpression", "Number_Value",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "validateAs", "Number",
"textHTML5Input", "Number" ) ),
"tableName", "dbo.OneForm_Values" ),
"RecordDate", new XVar( "name", "RecordDate",
"goodName", "RecordDate",
"strField", "RecordDate",
"index", 10,
"type", 135,
"sqlExpression", "RecordDate",
"viewFormats", new XVar( "view", new XVar( "format", "Custom",
"customExpression", "if (value == null || value == DBNull.Value)\r\n    return \"\";\r\n\r\nDateTime date;\r\n\r\nif (value is DateTime)\r\n{\r\n    date = (DateTime)value;\r\n}\r\nelse if (!DateTime.TryParse(value.ToString(), out date))\r\n{\r\n    return \"\";\r\n}\r\n\r\nSystem.Globalization.PersianCalendar pc =\r\n    new System.Globalization.PersianCalendar();\r\n\r\nreturn String.Format(\"{0:0000}/{1:00}/{2:00}\",\r\n    pc.GetYear(date),\r\n    pc.GetMonth(date),\r\n    pc.GetDayOfMonth(date));" ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Date",
"dateEditType", 11 ) ),
"tableName", "dbo.OneForm_Values" ),
"RecordUser", new XVar( "name", "RecordUser",
"goodName", "RecordUser",
"strField", "RecordUser",
"index", 11,
"type", 202,
"sqlExpression", "RecordUser",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Values" ) ),
"masterTables", new XVar( 0, new XVar( "table", "dbo.Branches",
"detailsKeys", new XVar( 0, "Branch" ),
"masterKeys", new XVar( 0, "Code" ) ),
1, new XVar( "table", "dbo.OneForm_Fields",
"detailsKeys", new XVar( 0, "Field_ID" ),
"masterKeys", new XVar( 0, "ID" ) ),
2, new XVar( "table", "dbo.OneForm_Fields_Groups",
"detailsKeys", new XVar( 0, "Group_ID" ),
"masterKeys", new XVar( 0, "ID" ) ) ),
"query", new XVar( "sql", "SELECT\n	ID,\n	Branch,\n	Group_ID,\n	Field_ID,\n	Number_Value,\n	ShortText_Value,\n	LongText_Value,\n	Check_Value,\n	File_Value,\n	RecordDate,\n	RecordUser\nFROM\n	dbo.OneForm_Values\nORDER BY\n	ID DESC\n",
"parsed", true,
"type", "SQLQuery",
"fieldList", new XVar( 0, new XVar( "sql", "ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "ID" ),
"encrypted", false,
"columnName", "ID" ),
1, new XVar( "sql", "Branch",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "Branch" ),
"encrypted", false,
"columnName", "Branch" ),
2, new XVar( "sql", "Group_ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "Group_ID" ),
"encrypted", false,
"columnName", "Group_ID" ),
3, new XVar( "sql", "Field_ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "Field_ID" ),
"encrypted", false,
"columnName", "Field_ID" ),
4, new XVar( "sql", "Number_Value",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "Number_Value" ),
"encrypted", false,
"columnName", "Number_Value" ),
5, new XVar( "sql", "ShortText_Value",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "ShortText_Value" ),
"encrypted", false,
"columnName", "ShortText_Value" ),
6, new XVar( "sql", "LongText_Value",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "LongText_Value" ),
"encrypted", false,
"columnName", "LongText_Value" ),
7, new XVar( "sql", "Check_Value",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "Check_Value" ),
"encrypted", false,
"columnName", "Check_Value" ),
8, new XVar( "sql", "File_Value",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "File_Value" ),
"encrypted", false,
"columnName", "File_Value" ),
9, new XVar( "sql", "RecordDate",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "RecordDate" ),
"encrypted", false,
"columnName", "RecordDate" ),
10, new XVar( "sql", "RecordUser",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "RecordUser" ),
"encrypted", false,
"columnName", "RecordUser" ) ),
"fromList", new XVar( 0, new XVar( "sql", "dbo.OneForm_Values",
"parsed", true,
"type", "FromListItem",
"table", new XVar( "sql", "dbo.OneForm_Values",
"parsed", true,
"type", "SQLTable",
"columns", new XVar( 0, "ID",
1, "Branch",
2, "Group_ID",
3, "Field_ID",
4, "Number_Value",
5, "ShortText_Value",
6, "LongText_Value",
7, "Check_Value",
8, "File_Value",
9, "RecordDate",
10, "RecordUser" ),
"name", "dbo.OneForm_Values" ),
"joinOn", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"joinList", new XVar( "sql", "",
"parsed", true,
"type", "JoinOn",
"field1", XVar.Array(),
"field2", XVar.Array() ),
"link", 0 ) ),
"where", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"groupBy", XVar.Array(),
"having", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"orderBy", new XVar( 0, new XVar( "sql", "ID DESC",
"parsed", true,
"type", "OrderByListItem",
"column", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values",
"name", "ID" ),
"asc", false,
"columnNumber", 1 ) ),
"colsIndex", new XVar( 0, new XVar( "fieldIndex", 0,
"orderByIndex", 0,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
1, new XVar( "fieldIndex", 1,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
2, new XVar( "fieldIndex", 2,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
3, new XVar( "fieldIndex", 3,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
4, new XVar( "fieldIndex", 4,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
5, new XVar( "fieldIndex", 5,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
6, new XVar( "fieldIndex", 6,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
7, new XVar( "fieldIndex", 7,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
8, new XVar( "fieldIndex", 8,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
9, new XVar( "fieldIndex", 9,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
10, new XVar( "fieldIndex", 10,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ) ),
"headSql", "SELECT",
"fieldListSql", "ID,\n	Branch,\n	Group_ID,\n	Field_ID,\n	Number_Value,\n	ShortText_Value,\n	LongText_Value,\n	Check_Value,\n	File_Value,\n	RecordDate,\n	RecordUser",
"fromListSql", "FROM\n	dbo.OneForm_Values",
"orderBySql", "ORDER BY\n	ID DESC",
"tailSql", "" ),
"hasJsEvents", true,
"originalTable", "dbo.OneForm_Values",
"originalPagesByType", new XVar( "add", new XVar( 0, "add" ),
"export", new XVar( 0, "export" ),
"import", new XVar( 0, "import" ),
"edit", new XVar( 0, "edit" ),
"view", new XVar( 0, "view" ),
"list", new XVar( 0, "list" ),
"print", new XVar( 0, "print" ),
"search", new XVar( 0, "search" ) ),
"originalPageTypes", new XVar( "add", "add",
"export", "export",
"import", "import",
"edit", "edit",
"view", "view",
"list", "list",
"print", "print",
"search", "search" ),
"originalDefaultPages", new XVar( "add", "add",
"export", "export",
"import", "import",
"edit", "edit",
"view", "view",
"list", "list",
"print", "print",
"search", "search" ),
"searchSettings", new XVar( "caseSensitiveSearch", false,
"searchableFields", new XVar( 0, "ID",
1, "Branch",
2, "Field_ID",
3, "ShortText_Value",
4, "LongText_Value",
5, "Check_Value",
6, "Group_ID",
7, "Number_Value",
8, "RecordDate",
9, "RecordUser" ),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false,
"googleLikeSearchFields", new XVar( 0, "ID",
1, "Branch",
2, "Field_ID",
3, "ShortText_Value",
4, "LongText_Value",
5, "Check_Value",
6, "Group_ID",
7, "Number_Value",
8, "RecordDate",
9, "RecordUser" ) ),
"connId", "conn",
"sortByFields", new XVar( "sortOrder", new XVar( 0, new XVar( "fields", new XVar( 0, new XVar( "field", "ID",
"desc", false ) ),
"label", new XVar( "field", "ID",
"table", "dbo.OneForm_Values",
"type", 3 ) ),
1, new XVar( "fields", new XVar( 0, new XVar( "field", "Branch",
"desc", false ) ),
"label", new XVar( "field", "Branch",
"table", "dbo.OneForm_Values",
"type", 3 ) ),
2, new XVar( "fields", new XVar( 0, new XVar( "field", "Field_ID",
"desc", false ) ),
"label", new XVar( "field", "Field_ID",
"table", "dbo.OneForm_Values",
"type", 3 ) ),
3, new XVar( "fields", new XVar( 0, new XVar( "field", "ShortText_Value",
"desc", false ) ),
"label", new XVar( "field", "ShortText_Value",
"table", "dbo.OneForm_Values",
"type", 3 ) ),
4, new XVar( "fields", new XVar( 0, new XVar( "field", "LongText_Value",
"desc", false ) ),
"label", new XVar( "field", "LongText_Value",
"table", "dbo.OneForm_Values",
"type", 3 ) ),
5, new XVar( "fields", new XVar( 0, new XVar( "field", "Check_Value",
"desc", false ) ),
"label", new XVar( "field", "Check_Value",
"table", "dbo.OneForm_Values",
"type", 3 ) ),
6, new XVar( "fields", new XVar( 0, new XVar( "field", "Group_ID",
"desc", false ) ),
"label", new XVar( "field", "Group_ID",
"table", "dbo.OneForm_Values",
"type", 3 ) ) ) ),
"clickActions", new XVar( "row", new XVar( "action", "noaction" ),
"fields", new XVar(  ) ),
"geoCoding", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ),
"whereTabs", XVar.Array(),
"labels", new XVar(  ),
"chartSettings", new XVar(  ),
"dataSourceOperations", new XVar(  ),
"calendarSettings", new XVar( "categoryColors", XVar.Array() ),
"ganttSettings", new XVar( "categoryColors", XVar.Array() ) ), "dbo.OneForm_Values");
			if(XVar.Equals(XVar.Pack(CommonFunctions.mlang_getcurrentlang()), XVar.Pack("Farsi")))
			{
				GlobalVars.runnerTableLabels.InitAndSetArrayItem(new XVar( "tableCaption", "اطلاعات",
"fieldLabels", new XVar( "ID", "شناسه",
"Branch", "شعبه",
"Field_ID", "عنوان",
"ShortText_Value", "متن کوتاه 50",
"LongText_Value", "متن بلند",
"Check_Value", "چک باکس",
"File_Value", "تصویر",
"Group_ID", "گروه سوال",
"Number_Value", "مقدار عددی",
"RecordDate", "تاریخ ثبت",
"RecordUser", "کاربر ثبت کننده" ),
"fieldTooltips", new XVar( "ID", "",
"Branch", "",
"Field_ID", "",
"ShortText_Value", "",
"LongText_Value", "",
"Check_Value", "",
"File_Value", "",
"Group_ID", "",
"Number_Value", "",
"RecordDate", "",
"RecordUser", "" ),
"fieldPlaceholders", new XVar( "ID", "",
"Branch", "",
"Field_ID", "",
"ShortText_Value", "",
"LongText_Value", "",
"Check_Value", "",
"File_Value", "",
"Group_ID", "",
"Number_Value", "",
"RecordDate", "",
"RecordUser", "" ),
"pageTitles", new XVar(  ) ), "dbo.OneForm_Values");
			}
		}
	}

}
