using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void table_OneForm_Fields()
		{
			GlobalVars.runnerTableSettings.InitAndSetArrayItem(new XVar( "name", "dbo.OneForm_Fields",
"shortName", "OneForm_Fields",
"pagesByType", new XVar( "add", new XVar( 0, "add" ),
"edit", new XVar( 0, "edit" ),
"list", new XVar( 0, "list" ),
"masterlist", new XVar( 0, "masterlist" ),
"masterprint", new XVar( 0, "masterprint" ),
"search", new XVar( 0, "search" ) ),
"pageTypes", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"defaultPages", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"audit", true,
"locking", true,
"afterEditDetails", "dbo.OneForm_Fields",
"afterAddDetail", "dbo.OneForm_Fields",
"detailsBadgeColor", "4169e1",
"pageSizeRecords", 10,
"pageSizeSelectorRecords", new XVar( 0, "10",
1, "20",
2, "30",
3, "50",
4, "100",
5, "150",
6, "500",
7, "all" ),
"sql", "SELECT\r\n	ID,\r\n	Group_ID,\r\n	FieldTitle,\r\n	FieldType,\r\n	Fields_Desc\r\nFROM\r\n	dbo.OneForm_Fields",
"keyFields", new XVar( 0, "ID" ),
"deviceHideFields", new XVar( "1", XVar.Array(),
"5", XVar.Array() ),
"fields", new XVar( "ID", new XVar( "name", "ID",
"goodName", "ID",
"strField", "ID",
"index", 1,
"type", 2,
"autoinc", true,
"sqlExpression", "ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Fields" ),
"Group_ID", new XVar( "name", "Group_ID",
"goodName", "Group_ID",
"strField", "Group_ID",
"index", 2,
"type", 2,
"sqlExpression", "Group_ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Lookup wizard",
"required", true,
"lookupType", 2,
"lookupTable", "dbo.OneForm_Fields_Groups",
"lookupTableConnection", "conn",
"lookupLinkField", "ID",
"lookupDisplayField", "Group_Name",
"lookupOrderBy", "Group_Name" ) ),
"tableName", "dbo.OneForm_Fields" ),
"FieldTitle", new XVar( "name", "FieldTitle",
"goodName", "FieldTitle",
"strField", "FieldTitle",
"index", 3,
"type", 202,
"sqlExpression", "FieldTitle",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Fields" ),
"FieldType", new XVar( "name", "FieldType",
"goodName", "FieldType",
"strField", "FieldType",
"index", 4,
"type", 202,
"sqlExpression", "FieldType",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Lookup wizard",
"required", true,
"lookupType", 0,
"lookupValues", new XVar( 0, "عدد",
1, "متن کوتاه",
2, "متن بلند",
3, "چک باکس",
4, "فایل" ),
"lookupControlType", 4 ) ),
"tableName", "dbo.OneForm_Fields" ),
"Fields_Desc", new XVar( "name", "Fields_Desc",
"goodName", "Fields_Desc",
"strField", "Fields_Desc",
"index", 5,
"type", 202,
"sqlExpression", "Fields_Desc",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Text area",
"defaultValue", " @\"متن کوتاه :\nمتن بلند:\nچک باکس:\nمقدار عددی:\";",
"textareaHeight", 150 ) ),
"tableName", "dbo.OneForm_Fields" ) ),
"masterTables", new XVar( 0, new XVar( "table", "dbo.OneForm_Fields_Groups",
"detailsKeys", new XVar( 0, "Group_ID" ),
"masterKeys", new XVar( 0, "ID" ) ) ),
"detailsTables", new XVar( 0, "dbo.OneForm_Values" ),
"query", new XVar( "sql", "SELECT\r\n	ID,\r\n	Group_ID,\r\n	FieldTitle,\r\n	FieldType,\r\n	Fields_Desc\r\nFROM\r\n	dbo.OneForm_Fields",
"parsed", true,
"type", "SQLQuery",
"fieldList", new XVar( 0, new XVar( "sql", "ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields",
"name", "ID" ),
"encrypted", false,
"columnName", "ID" ),
1, new XVar( "sql", "Group_ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields",
"name", "Group_ID" ),
"encrypted", false,
"columnName", "Group_ID" ),
2, new XVar( "sql", "FieldTitle",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields",
"name", "FieldTitle" ),
"encrypted", false,
"columnName", "FieldTitle" ),
3, new XVar( "sql", "FieldType",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields",
"name", "FieldType" ),
"encrypted", false,
"columnName", "FieldType" ),
4, new XVar( "sql", "Fields_Desc",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields",
"name", "Fields_Desc" ),
"encrypted", false,
"columnName", "Fields_Desc" ) ),
"fromList", new XVar( 0, new XVar( "sql", "dbo.OneForm_Fields",
"parsed", true,
"type", "FromListItem",
"table", new XVar( "sql", "dbo.OneForm_Fields",
"parsed", true,
"type", "SQLTable",
"columns", new XVar( 0, "ID",
1, "Group_ID",
2, "FieldTitle",
3, "FieldType",
4, "Fields_Desc" ),
"name", "dbo.OneForm_Fields" ),
"joinOn", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"joinList", new XVar( "sql", "",
"parsed", true,
"type", "JoinOn",
"field1", XVar.Array(),
"field2", XVar.Array() ),
"link", 0 ) ),
"where", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"groupBy", XVar.Array(),
"having", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"orderBy", XVar.Array(),
"colsIndex", new XVar( 0, new XVar( "fieldIndex", 0,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
1, new XVar( "fieldIndex", 1,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
2, new XVar( "fieldIndex", 2,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
3, new XVar( "fieldIndex", 3,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
4, new XVar( "fieldIndex", 4,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ) ),
"headSql", "SELECT",
"fieldListSql", "ID,\r\n	Group_ID,\r\n	FieldTitle,\r\n	FieldType,\r\n	Fields_Desc",
"fromListSql", "FROM\r\n	dbo.OneForm_Fields",
"orderBySql", "",
"tailSql", "" ),
"originalTable", "dbo.OneForm_Fields",
"originalPagesByType", new XVar( "add", new XVar( 0, "add" ),
"edit", new XVar( 0, "edit" ),
"list", new XVar( 0, "list" ),
"masterlist", new XVar( 0, "masterlist" ),
"masterprint", new XVar( 0, "masterprint" ),
"search", new XVar( 0, "search" ) ),
"originalPageTypes", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"originalDefaultPages", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"searchSettings", new XVar( "caseSensitiveSearch", false,
"searchableFields", new XVar( 0, "ID",
1, "Group_ID",
2, "FieldTitle",
3, "FieldType",
4, "Fields_Desc" ),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false,
"googleLikeSearchFields", new XVar( 0, "ID",
1, "Group_ID",
2, "FieldTitle",
3, "FieldType",
4, "Fields_Desc" ) ),
"connId", "conn",
"clickActions", new XVar( "row", new XVar( "action", "noaction" ),
"fields", new XVar(  ) ),
"geoCoding", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ),
"whereTabs", XVar.Array(),
"labels", new XVar(  ),
"chartSettings", new XVar(  ),
"dataSourceOperations", new XVar(  ),
"calendarSettings", new XVar( "categoryColors", XVar.Array() ),
"ganttSettings", new XVar( "categoryColors", XVar.Array() ) ), "dbo.OneForm_Fields");
			if(XVar.Equals(XVar.Pack(CommonFunctions.mlang_getcurrentlang()), XVar.Pack("Farsi")))
			{
				GlobalVars.runnerTableLabels.InitAndSetArrayItem(new XVar( "tableCaption", "عناوین فرم",
"fieldLabels", new XVar( "ID", "شناسه",
"Group_ID", "فرم",
"FieldTitle", "عنوان",
"FieldType", "نوع فیلد",
"Fields_Desc", "شرح فیلد ها" ),
"fieldTooltips", new XVar( "ID", "",
"Group_ID", "",
"FieldTitle", "",
"FieldType", "",
"Fields_Desc", "" ),
"fieldPlaceholders", new XVar( "ID", "",
"Group_ID", "",
"FieldTitle", "",
"FieldType", "",
"Fields_Desc", "" ),
"pageTitles", new XVar(  ) ), "dbo.OneForm_Fields");
			}
		}
	}

}
