using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void table_OneForm_Fields_Groups()
		{
			GlobalVars.runnerTableSettings.InitAndSetArrayItem(new XVar( "name", "dbo.OneForm_Fields_Groups",
"shortName", "OneForm_Fields_Groups",
"pagesByType", new XVar( "add", new XVar( 0, "add" ),
"edit", new XVar( 0, "edit" ),
"list", new XVar( 0, "list" ),
"masterlist", new XVar( 0, "masterlist" ),
"masterprint", new XVar( 0, "masterprint" ),
"search", new XVar( 0, "search" ) ),
"pageTypes", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"defaultPages", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"audit", true,
"locking", true,
"afterEditDetails", "dbo.OneForm_Fields_Groups",
"afterAddDetail", "dbo.OneForm_Fields_Groups",
"detailsBadgeColor", "d2691e",
"pageSizeRecords", 10,
"pageSizeSelectorRecords", new XVar( 0, "10",
1, "20",
2, "30",
3, "50",
4, "100",
5, "150",
6, "500",
7, "all" ),
"sql", "SELECT\r\n	ID,\r\n	Group_Name\r\nFROM\r\n	dbo.OneForm_Fields_Groups",
"keyFields", new XVar( 0, "ID" ),
"deviceHideFields", new XVar( "1", XVar.Array(),
"5", XVar.Array() ),
"fields", new XVar( "ID", new XVar( "name", "ID",
"goodName", "ID",
"strField", "ID",
"index", 1,
"type", 2,
"autoinc", true,
"sqlExpression", "ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Fields_Groups" ),
"Group_Name", new XVar( "name", "Group_Name",
"goodName", "Group_Name",
"strField", "Group_Name",
"index", 2,
"type", 202,
"sqlExpression", "Group_Name",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Fields_Groups" ) ),
"detailsTables", new XVar( 0, "dbo.OneForm_Fields",
1, "dbo.OneForm_Values" ),
"query", new XVar( "sql", "SELECT\r\n	ID,\r\n	Group_Name\r\nFROM\r\n	dbo.OneForm_Fields_Groups",
"parsed", true,
"type", "SQLQuery",
"fieldList", new XVar( 0, new XVar( "sql", "ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields_Groups",
"name", "ID" ),
"encrypted", false,
"columnName", "ID" ),
1, new XVar( "sql", "Group_Name",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Fields_Groups",
"name", "Group_Name" ),
"encrypted", false,
"columnName", "Group_Name" ) ),
"fromList", new XVar( 0, new XVar( "sql", "dbo.OneForm_Fields_Groups",
"parsed", true,
"type", "FromListItem",
"table", new XVar( "sql", "dbo.OneForm_Fields_Groups",
"parsed", true,
"type", "SQLTable",
"columns", new XVar( 0, "ID",
1, "Group_Name" ),
"name", "dbo.OneForm_Fields_Groups" ),
"joinOn", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"joinList", new XVar( "sql", "",
"parsed", true,
"type", "JoinOn",
"field1", XVar.Array(),
"field2", XVar.Array() ),
"link", 0 ) ),
"where", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"groupBy", XVar.Array(),
"having", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"orderBy", XVar.Array(),
"colsIndex", new XVar( 0, new XVar( "fieldIndex", 0,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
1, new XVar( "fieldIndex", 1,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ) ),
"headSql", "SELECT",
"fieldListSql", "ID,\r\n	Group_Name",
"fromListSql", "FROM\r\n	dbo.OneForm_Fields_Groups",
"orderBySql", "",
"tailSql", "" ),
"originalTable", "dbo.OneForm_Fields_Groups",
"originalPagesByType", new XVar( "add", new XVar( 0, "add" ),
"edit", new XVar( 0, "edit" ),
"list", new XVar( 0, "list" ),
"masterlist", new XVar( 0, "masterlist" ),
"masterprint", new XVar( 0, "masterprint" ),
"search", new XVar( 0, "search" ) ),
"originalPageTypes", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"originalDefaultPages", new XVar( "add", "add",
"edit", "edit",
"list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"searchSettings", new XVar( "caseSensitiveSearch", false,
"searchableFields", new XVar( 0, "ID",
1, "Group_Name" ),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false,
"googleLikeSearchFields", new XVar( 0, "ID",
1, "Group_Name" ) ),
"connId", "conn",
"clickActions", new XVar( "row", new XVar( "action", "noaction" ),
"fields", new XVar(  ) ),
"geoCoding", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ),
"whereTabs", XVar.Array(),
"labels", new XVar(  ),
"chartSettings", new XVar(  ),
"dataSourceOperations", new XVar(  ),
"calendarSettings", new XVar( "categoryColors", XVar.Array() ),
"ganttSettings", new XVar( "categoryColors", XVar.Array() ) ), "dbo.OneForm_Fields_Groups");
			if(XVar.Equals(XVar.Pack(CommonFunctions.mlang_getcurrentlang()), XVar.Pack("Farsi")))
			{
				GlobalVars.runnerTableLabels.InitAndSetArrayItem(new XVar( "tableCaption", "فرم ها",
"fieldLabels", new XVar( "ID", "شناسه",
"Group_Name", "عنوان گروه سوال" ),
"fieldTooltips", new XVar( "ID", "",
"Group_Name", "" ),
"fieldPlaceholders", new XVar( "ID", "",
"Group_Name", "" ),
"pageTitles", new XVar(  ) ), "dbo.OneForm_Fields_Groups");
			}
		}
	}

}
