using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void table_OneForm_Values_Images()
		{
			GlobalVars.runnerTableSettings.InitAndSetArrayItem(new XVar( "name", "dbo.OneForm_Values_Images",
"shortName", "OneForm_Values_Images",
"pagesByType", new XVar( "add", new XVar( 0, "add" ),
"list", new XVar( 0, "list" ),
"print", new XVar( 0, "print" ),
"edit", new XVar( 0, "edit" ),
"view", new XVar( 0, "view" ),
"search", new XVar( 0, "search" ) ),
"pageTypes", new XVar( "add", "add",
"list", "list",
"print", "print",
"edit", "edit",
"view", "view",
"search", "search" ),
"defaultPages", new XVar( "add", "add",
"list", "list",
"print", "print",
"edit", "edit",
"view", "view",
"search", "search" ),
"afterEditDetails", "dbo.OneForm_Values_Images",
"afterAddDetail", "dbo.OneForm_Values_Images",
"detailsBadgeColor", "00c2c5",
"orderInfo", new XVar( 0, new XVar( "index", 1,
"dir", "DESC",
"field", "ID" ) ),
"sql", "SELECT\n	ID,\n	OneForm_Value_ID,\n	Image_Data,\n	thumbnails\nFROM\n	dbo.OneForm_Values_Images\nORDER BY\n	ID DESC\n",
"keyFields", new XVar( 0, "ID" ),
"deviceHideFields", new XVar( "1", XVar.Array(),
"5", XVar.Array() ),
"fields", new XVar( "ID", new XVar( "name", "ID",
"goodName", "ID",
"strField", "ID",
"index", 1,
"type", 3,
"autoinc", true,
"sqlExpression", "ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Values_Images" ),
"OneForm_Value_ID", new XVar( "name", "OneForm_Value_ID",
"goodName", "OneForm_Value_ID",
"strField", "OneForm_Value_ID",
"index", 2,
"type", 3,
"sqlExpression", "OneForm_Value_ID",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.OneForm_Values_Images" ),
"Image_Data", new XVar( "name", "Image_Data",
"goodName", "Image_Data",
"strField", "Image_Data",
"index", 3,
"type", 204,
"sqlExpression", "Image_Data",
"viewFormats", new XVar( "view", new XVar( "format", "Database Image",
"imageShowThumbnail", true ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Database image",
"required", true,
"fileCreateThumbnail", true,
"fileThumbnailSize", 100,
"fileTypes", new XVar( 0, "bmp",
1, "jpg",
2, "png",
3, "gif",
4, "jpeg" ),
"fileThumbnailField", "thumbnails" ) ),
"tableName", "dbo.OneForm_Values_Images" ),
"thumbnails", new XVar( "name", "thumbnails",
"goodName", "thumbnails",
"strField", "thumbnails",
"index", 4,
"type", 204,
"sqlExpression", "thumbnails",
"viewFormats", new XVar( "view", new XVar( "format", "Database Image" ) ),
"editFormats", new XVar( "edit", new XVar( "format", "Database image" ) ),
"tableName", "dbo.OneForm_Values_Images" ) ),
"masterTables", new XVar( 0, new XVar( "table", "dbo.OneForm_Values",
"detailsKeys", new XVar( 0, "OneForm_Value_ID" ),
"masterKeys", new XVar( 0, "ID" ) ) ),
"query", new XVar( "sql", "SELECT\n	ID,\n	OneForm_Value_ID,\n	Image_Data,\n	thumbnails\nFROM\n	dbo.OneForm_Values_Images\nORDER BY\n	ID DESC\n",
"parsed", true,
"type", "SQLQuery",
"fieldList", new XVar( 0, new XVar( "sql", "ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values_Images",
"name", "ID" ),
"encrypted", false,
"columnName", "ID" ),
1, new XVar( "sql", "OneForm_Value_ID",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values_Images",
"name", "OneForm_Value_ID" ),
"encrypted", false,
"columnName", "OneForm_Value_ID" ),
2, new XVar( "sql", "Image_Data",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values_Images",
"name", "Image_Data" ),
"encrypted", false,
"columnName", "Image_Data" ),
3, new XVar( "sql", "thumbnails",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values_Images",
"name", "thumbnails" ),
"encrypted", false,
"columnName", "thumbnails" ) ),
"fromList", new XVar( 0, new XVar( "sql", "dbo.OneForm_Values_Images",
"parsed", true,
"type", "FromListItem",
"table", new XVar( "sql", "dbo.OneForm_Values_Images",
"parsed", true,
"type", "SQLTable",
"columns", new XVar( 0, "ID",
1, "OneForm_Value_ID",
2, "Image_Data",
3, "thumbnails" ),
"name", "dbo.OneForm_Values_Images" ),
"joinOn", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"joinList", new XVar( "sql", "",
"parsed", true,
"type", "JoinOn",
"field1", XVar.Array(),
"field2", XVar.Array() ),
"link", 0 ) ),
"where", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"groupBy", XVar.Array(),
"having", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"orderBy", new XVar( 0, new XVar( "sql", "ID DESC",
"parsed", true,
"type", "OrderByListItem",
"column", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.OneForm_Values_Images",
"name", "ID" ),
"asc", false,
"columnNumber", 1 ) ),
"colsIndex", new XVar( 0, new XVar( "fieldIndex", 0,
"orderByIndex", 0,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
1, new XVar( "fieldIndex", 1,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
2, new XVar( "fieldIndex", 2,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
3, new XVar( "fieldIndex", 3,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ) ),
"headSql", "SELECT",
"fieldListSql", "ID,\n	OneForm_Value_ID,\n	Image_Data,\n	thumbnails",
"fromListSql", "FROM\n	dbo.OneForm_Values_Images",
"orderBySql", "ORDER BY\n	ID DESC",
"tailSql", "" ),
"galleryMode", 3,
"originalTable", "dbo.OneForm_Values_Images",
"originalPagesByType", new XVar( "add", new XVar( 0, "add" ),
"list", new XVar( 0, "list" ),
"print", new XVar( 0, "print" ),
"edit", new XVar( 0, "edit" ),
"view", new XVar( 0, "view" ),
"search", new XVar( 0, "search" ) ),
"originalPageTypes", new XVar( "add", "add",
"list", "list",
"print", "print",
"edit", "edit",
"view", "view",
"search", "search" ),
"originalDefaultPages", new XVar( "add", "add",
"list", "list",
"print", "print",
"edit", "edit",
"view", "view",
"search", "search" ),
"searchSettings", new XVar( "caseSensitiveSearch", false,
"searchableFields", new XVar( 0, "ID",
1, "OneForm_Value_ID" ),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false,
"googleLikeSearchFields", new XVar( 0, "ID",
1, "OneForm_Value_ID" ) ),
"connId", "conn",
"clickActions", new XVar( "row", new XVar( "action", "noaction" ),
"fields", new XVar(  ) ),
"geoCoding", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ),
"whereTabs", XVar.Array(),
"labels", new XVar(  ),
"chartSettings", new XVar(  ),
"dataSourceOperations", new XVar(  ),
"calendarSettings", new XVar( "categoryColors", XVar.Array() ),
"ganttSettings", new XVar( "categoryColors", XVar.Array() ) ), "dbo.OneForm_Values_Images");
			if(XVar.Equals(XVar.Pack(CommonFunctions.mlang_getcurrentlang()), XVar.Pack("Farsi")))
			{
				GlobalVars.runnerTableLabels.InitAndSetArrayItem(new XVar( "tableCaption", "تصاویر",
"fieldLabels", new XVar( "ID", "شناسه",
"OneForm_Value_ID", "سوال",
"Image_Data", "تصویر",
"thumbnails", "بند انگشتی" ),
"fieldTooltips", new XVar( "ID", "",
"OneForm_Value_ID", "",
"Image_Data", "",
"thumbnails", "" ),
"fieldPlaceholders", new XVar( "ID", "",
"OneForm_Value_ID", "",
"Image_Data", "",
"thumbnails", "" ),
"pageTitles", new XVar(  ) ), "dbo.OneForm_Values_Images");
			}
		}
	}

}
