using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void table_Branches()
		{
			GlobalVars.runnerTableSettings.InitAndSetArrayItem(new XVar( "name", "dbo.Branches",
"shortName", "Branches",
"pagesByType", new XVar( "list", new XVar( 0, "list" ),
"masterlist", new XVar( 0, "masterlist" ),
"masterprint", new XVar( 0, "masterprint" ),
"search", new XVar( 0, "search" ) ),
"pageTypes", new XVar( "list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"defaultPages", new XVar( "list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"afterEditDetails", "dbo.Branches",
"afterAddDetail", "dbo.Branches",
"detailsBadgeColor", "bc8f8f",
"pageSizeRecords", 10,
"pageSizeSelectorRecords", new XVar( 0, "10",
1, "20",
2, "30",
3, "50",
4, "100",
5, "150",
6, "500",
7, "all" ),
"resizeColumns", true,
"sql", "SELECT\n	Code,\n	BrName\nFROM\n	dbo.Branches\n",
"keyFields", new XVar( 0, "Code" ),
"deviceHideFields", new XVar( "1", XVar.Array(),
"5", XVar.Array() ),
"fields", new XVar( "Code", new XVar( "name", "Code",
"goodName", "Code",
"strField", "Code",
"index", 1,
"type", 3,
"sqlExpression", "Code",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.Branches" ),
"BrName", new XVar( "name", "BrName",
"goodName", "BrName",
"strField", "BrName",
"index", 2,
"type", 202,
"sqlExpression", "BrName",
"viewFormats", new XVar( "view", new XVar(  ) ),
"editFormats", new XVar( "edit", new XVar(  ) ),
"tableName", "dbo.Branches" ) ),
"detailsTables", new XVar( 0, "dbo.OneForm_Values" ),
"query", new XVar( "sql", "SELECT\n	Code,\n	BrName\nFROM\n	dbo.Branches\n",
"parsed", true,
"type", "SQLQuery",
"fieldList", new XVar( 0, new XVar( "sql", "Code",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.Branches",
"name", "Code" ),
"encrypted", false,
"columnName", "Code" ),
1, new XVar( "sql", "BrName",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "",
"parsed", true,
"type", "SQLField",
"table", "dbo.Branches",
"name", "BrName" ),
"encrypted", false,
"columnName", "BrName" ) ),
"fromList", new XVar( 0, new XVar( "sql", "dbo.Branches",
"parsed", true,
"type", "FromListItem",
"table", new XVar( "sql", "dbo.Branches",
"parsed", true,
"type", "SQLTable",
"columns", new XVar( 0, "Code",
1, "BrName",
2, "Email",
3, "DialUpPhone" ),
"name", "dbo.Branches" ),
"joinOn", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"joinList", new XVar( "sql", "",
"parsed", true,
"type", "JoinOn",
"field1", XVar.Array(),
"field2", XVar.Array() ),
"link", 0 ) ),
"where", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"groupBy", XVar.Array(),
"having", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"orderBy", XVar.Array(),
"colsIndex", new XVar( 0, new XVar( "fieldIndex", 0,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ),
1, new XVar( "fieldIndex", 1,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ) ),
"headSql", "SELECT",
"fieldListSql", "Code,\n	BrName",
"fromListSql", "FROM\n	dbo.Branches",
"orderBySql", "",
"tailSql", "" ),
"originalTable", "dbo.Branches",
"originalPagesByType", new XVar( "list", new XVar( 0, "list" ),
"masterlist", new XVar( 0, "masterlist" ),
"masterprint", new XVar( 0, "masterprint" ),
"search", new XVar( 0, "search" ) ),
"originalPageTypes", new XVar( "list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"originalDefaultPages", new XVar( "list", "list",
"masterlist", "masterlist",
"masterprint", "masterprint",
"search", "search" ),
"searchSettings", new XVar( "caseSensitiveSearch", false,
"searchableFields", new XVar( 0, "Code",
1, "BrName" ),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false,
"googleLikeSearchFields", new XVar( 0, "Code",
1, "BrName" ) ),
"connId", "conn",
"clickActions", new XVar( "row", new XVar( "action", "noaction" ),
"fields", new XVar(  ) ),
"geoCoding", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ),
"whereTabs", XVar.Array(),
"labels", new XVar(  ),
"chartSettings", new XVar(  ),
"dataSourceOperations", new XVar(  ),
"calendarSettings", new XVar( "categoryColors", XVar.Array() ),
"ganttSettings", new XVar( "categoryColors", XVar.Array() ) ), "dbo.Branches");
			if(XVar.Equals(XVar.Pack(CommonFunctions.mlang_getcurrentlang()), XVar.Pack("Farsi")))
			{
				GlobalVars.runnerTableLabels.InitAndSetArrayItem(new XVar( "tableCaption", "شعب",
"fieldLabels", new XVar( "Code", "کد مهرگستر",
"BrName", "نام شعبه" ),
"fieldTooltips", new XVar( "Code", "",
"BrName", "" ),
"fieldPlaceholders", new XVar( "Code", "",
"BrName", "" ),
"pageTitles", new XVar(  ) ), "dbo.Branches");
			}
		}
	}

}
