using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void dbtable_dbo_oneform_values()
		{
			GlobalVars.runnerDbTableInfo.InitAndSetArrayItem(new XVar( "type", 0,
"foreignKeys", XVar.Array(),
"fields", new XVar( 0, new XVar( "name", "ID",
"type", 3,
"size", 10,
"scale", 0,
"typeName", "int",
"nullable", false,
"autoinc", true,
"defaultValueSQL", "",
"defaultValue", "" ),
1, new XVar( "name", "Branch",
"type", 2,
"size", 5,
"scale", 0,
"typeName", "smallint",
"nullable", false,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
2, new XVar( "name", "Group_ID",
"type", 2,
"size", 5,
"scale", 0,
"typeName", "smallint",
"nullable", false,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
3, new XVar( "name", "Field_ID",
"type", 2,
"size", 5,
"scale", 0,
"typeName", "smallint",
"nullable", false,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
4, new XVar( "name", "Number_Value",
"type", 202,
"size", 100,
"scale", null,
"typeName", "nvarchar",
"nullable", true,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
5, new XVar( "name", "ShortText_Value",
"type", 202,
"size", 200,
"scale", null,
"typeName", "nvarchar",
"nullable", true,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
6, new XVar( "name", "LongText_Value",
"type", 202,
"size", 2147483646,
"scale", null,
"typeName", "nvarchar",
"nullable", true,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
7, new XVar( "name", "Check_Value",
"type", 11,
"size", 1,
"scale", null,
"typeName", "bit",
"nullable", true,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
8, new XVar( "name", "File_Value",
"type", 205,
"size", 2147483647,
"scale", null,
"typeName", "image",
"nullable", true,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ),
9, new XVar( "name", "RecordDate",
"type", 135,
"size", 16,
"scale", 3,
"typeName", "datetime",
"nullable", false,
"autoinc", false,
"defaultValueSQL", "getdate()",
"defaultValue", "CURRENT_TIMESTAMP" ),
10, new XVar( "name", "RecordUser",
"type", 202,
"size", 100,
"scale", null,
"typeName", "nvarchar",
"nullable", false,
"autoinc", false,
"defaultValueSQL", "",
"defaultValue", "" ) ),
"primaryKeys", new XVar( 0, "ID" ),
"uniqueFields", XVar.Array(),
"name", "OneForm_Values",
"schema", "dbo" ), "dbo_oneform_values");
		}
	}

}
